var leaderCntr = 0;

leaders = [
  new leader (leaderCntr++, undefined, "Napoleon"       , "Emperor"        , "french", "infantry-leader", 4, true ,10, 6, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Drouot"         , "Old Guard"      , "french", "infantry-leader", 4, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Soult"          , "Old Guard"      , "french", "infantry-leader", 4, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Oudinot"        , "I Young Guard"  , "french", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Mortier"        , "II Young Guard" , "french", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Vandamme"       , "I Corps"        , "french", "infantry-leader", 2, true , 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Victor"         , "II Corps"       , "french", "infantry-leader", 2, false, 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Ney"            , "III Corps"      , "french", "infantry-leader", 3, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Souham"         , "III Corps"      , "french", "infantry-leader", 2, false, 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Betrand"        , "IV Corps"       , "french", "infantry-leader", 3, true,  6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Lauriston"      , "V Corps"        , "french", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Marmont"        , "VI Corps"       , "french", "infantry-leader", 3, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Reynier"        , "VII Corps"      , "french", "infantry-leader", 4, true , 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Poniatowski"    , "VIII Corps"     , "french", "infantry-leader", 4, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Augereau"       , "IX Corps"       , "french", "infantry-leader", 2, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "MacDonald"      , "XI Corps"       , "french", "infantry-leader", 4, true , 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Gerard"         , "XI Corps"       , "french", "infantry-leader", 3, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Oudinot"        , "XII Corps"      , "french", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "St. Cyr"        , "XIV Corps"      , "french", "infantry-leader", 5, false, 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Girard"         , "Ad Hoc"         , "french", "infantry-leader", 3, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Eugene"         , "Armee de l'Elbe", "french", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),            
  new leader (leaderCntr++, undefined, "Bessieres"      , "Guard Cavalry"  , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Nansouty"       , "Guard Cavalry"  , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Latour-Maubourg", "I Cavalry"      , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Sebastiani"     , "II Cavalry"     , "french", "cavalry-leader",  5, false, 3, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Arrighi"        , "III Cavalry"    , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Kellerman"      , "IV Cavalry"     , "french", "cavalry-leader",  4, false, 1, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "L'Heritier"     , "V Cavalry"      , "french", "cavalry-leader",  4, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Murat"          , "Cavalry Reserve", "french", "cavalry-leader",  4, false, 6, 3, "column", 0, 0, "NE"),

  new leader (leaderCntr++, undefined, "Bluecher"  , "I Corps"    , "prussian", "infantry-leader", 4, true , 8, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Kleist"    , "II Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Bulow"     , "III Corps"  , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Yorck"     , "II Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Tauenzien" , "IV Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Truebezkov", "III Cavalry", "prussian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Korff"     , "I Cavalry"  , "prussian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),

  new leader (leaderCntr++, undefined, "Schwarzenberg", "XXXX"     , "austrian", "infantry-leader", 2, true , 6, 4, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Colloredo"    , "I Corps"  , "austrian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Gyulai"       , "III Corps", "austrian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Meerveldt"    , "II Corps" , "austrian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Klenau"       , "IV Corps" , "austrian", "infantry-leader", 1, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Hesse Homburg", "Reserve"  , "austrian", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),

  new leader (leaderCntr++, undefined, "Barclay de Tolly" , ""                  , "russian", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Bennigsen"        , "I Corps"           , "russian", "infantry-leader", 2, false, 4, 4, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Doctorov"         , "I Corps"           , "russian", "infantry-leader", 1, false, 6, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Ostermann-Tolstoj", "Militia"           , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Langeron"         , ""                  , "russian", "infantry-leader", 2, false, 5, 4, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Olsufiew"         , "IX Corps"          , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "St Priest"        , "VII Corps"         , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Scherbatow"       , "VI Corps"          , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Kapzewitsch"      , "X Corps"           , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Osten-Sacken"     , "XI Corps"          , "russian", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Wittgenstein"     , ""                  , "russian", "infantry-leader", 2, false, 5, 3, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Gortchakow"       , "I Infantry"        , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Eugen"            , "II Infantry"       , "russian", "infantry-leader", 2, false, 2, 1, "column", 0, 0, "NE"),   
  new leader (leaderCntr++, undefined, "Konstantin"       , "Guards and Reserve", "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),    
  new leader (leaderCntr++, undefined, "Miloradowitch"    , "II Corps"          , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Rajewski"         , "III Grenadiers"    , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),   
  new leader (leaderCntr++, undefined, "Yermolow"         , "V Guards"          , "russian", "infantry-leader", 1, false, 3, 1, "column", 0, 0, "NE"), 
  new leader (leaderCntr++, undefined, "Winzingerode"     , "II Corps"          , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Woronzow"         , "XIV Corps"         , "russian", "infantry-leader", 1, false, 4, 2, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Markow"           , "IV Infantry"       , "russian", "infantry-leader", 4, false, 2, 1, "column", 0, 0, "NE"),             
  new leader (leaderCntr++, undefined, "Galitzin"         , "II Cuirassiers"    , "russian", "cavalry-leader" , 4, false, 4, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Pahlen"           , "IV Cavalry"        , "russian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Wasiltchikow"     , "IV Cavalry"        , "russian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),

  new leader (leaderCntr++, undefined, "Bernadotte", "XXXX"   , "swedish", "infantry-leader", 1, false, 4, 4, "column", 0, 0, "NE"),
  new leader (leaderCntr++, undefined, "Stedingk"  , "I Corps", "swedish", "infantry-leader", 1, false, 5, 2, "column", 0, 0, "NE")
];


var unitCntr = 0; 
var units = [
  new InfantryUnit (unitCntr++, "1st OG"  , "Roguet"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd OG"  , "Curial"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd YGde", "Barrois"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd YGde", "Delaborde"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "4th YGde", "Roguet"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "1st"     , "Philippon"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd"     , "Dumonceau"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"     , "Teste"       , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "4th"     , "Dubreton"    , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "5th"     , "Dufour"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "6th"     , "Vial"        , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "8th"     , "Brayer"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "9th"     , "Brenier"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "10th"    , "Albert"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "11th"    , "Richard"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "16th"    , "Maison"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "13rd"    , "Patchod"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "17th"    , "Puthod"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "18th"    , "Lagrange"    , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "19th"    , "Rochambeau"  , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "20th"    , "Compans"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "21st"    , "Bonet"       , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "22nd"    , "Friederich"  , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "23rd"    , "Laboissiere" , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "31st"    , "Ledru des"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "32nd"    , "Durutte"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "35th"    , "Frassinet"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "36th"    , "Charpentier" , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "14th"    , "Lorencez"    , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "42nd"    , "Creutzer"    , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "43rd"    , "Claparede"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "44th"    , "Berthezene"  , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "45th"    , "Razout"      , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "51st"    , "Turreau"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "52nd"    , "Semelle"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Lefol"   , ""            , "french", "Division", 0),

  new InfantryUnit (unitCntr++, "Glogau"    , "Laplane"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Dresden"   , "Durosnel"  , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Leipzig"   , "Margaron"  , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Magdeburg" , "Lanusse"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Magdeburg" , "Lemoine"   , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Torgau"    , "Lauer"     , "french", "Division", 0),
  new InfantryUnit (unitCntr++, "Wittenberg", "Lapoype"   , "french", "Division", 0),

  new CavalryUnit (unitCntr++, "1st Ornano"       , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Lefebvre"     , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "3rd Walther"      , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "10th Jacquet"     , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "21st Corbineau"   , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "1st Hvy Bordessol", "french", "Division", 0),
  new CavalryUnit (unitCntr++, "1st Light Bruyere", "french", "Division", 0),
  new CavalryUnit (unitCntr++, "3rd Hvy Doumerc"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "3rd Lt Chastel"   , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Hvy Wattier"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Lt d'Hurbal"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "4th Lt Exelmans"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "4th Hvy Defrance" , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "5th Lt Lorge"     , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "6th Lt Fournier"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "6th Bruno"        , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "5th Hvy Collaert" , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "6th Hvy Milhaud"  , "french", "Division", 0),
  new CavalryUnit (unitCntr++, "9th Lt Subervie"  , "french", "Division", 0),
  new ArtilleryUnit (unitCntr++, "Guard Artillery"  , "french", "Division", 0),
  new ArtilleryUnit (unitCntr++, "Artillery Reserve", "french", "Division", 0),
  new ArtilleryUnit (unitCntr++, "Artillery Reserve", "french", "Division", 0),
  new ArtilleryUnit (unitCntr++, "Artillery Reserve", "french", "Division", 0),

  new InfantryUnit (unitCntr++, "15th", "Peyri"      , "german", "Division", 0),
  new InfantryUnit (unitCntr++, "24th", "Lecoq"      , "german", "Division", 0),
  new InfantryUnit (unitCntr++, "25th", "Sahr"       , "german", "Division", 0),
  new InfantryUnit (unitCntr++, "38th", "Franquemont", "german", "Division", 0),
  new InfantryUnit (unitCntr++, "39th", "Marchand"   , "german", "Division", 0),
  new InfantryUnit (unitCntr++, "IV"  , ""           , "german", "Division", 0),

  new CavalryUnit (unitCntr++, ""        , "Briche-J" , "german", "Brigade", 0),
  new CavalryUnit (unitCntr++, "25th Cav", "Norman"   , "german", "Brigade", 0),
  new CavalryUnit (unitCntr++, "26th Cav", "Gablenz"  , "german", "Brigade", 0),
  new CavalryUnit (unitCntr++, "28th Cav", "Montbrun" , "german", "Brigade", 0),
  new CavalryUnit (unitCntr++, "29th Cav", "Raglowich", "german", "Brigade", 0),

  // Prussians
  Sonew InfantryUnit (unitCntr++, "1st"   , "Losthin"    , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd"   , "Warburg"    , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "7th"   , "Weltzien"   , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "8th"   , "Girsa"      , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "9th"   , "Kluex"      , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "10th"  , "Roeder"     , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "11th"  , "Zieten"     , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "12th"  , "August"     , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"   , "H Homburg"  , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "4th"   , "Thuemen"    , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "5th"   , "Borstell"   , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "6th"   , "Krafft"     , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "Lander", "Dobschutz"  , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "Lander", "Hirschfeld" , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "Lander", "Putlitz"    , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "Lander", "Wobeser"    , "prussian", "Division", 0),
  new InfantryUnit (unitCntr++, "Garde" , "Alvensleben", "prussian", "Division", 0),

  new CavalryUnit (unitCntr++, "Reserve", "Oppenheimer", "prussian", "Division", 0),
  new CavalryUnit (unitCntr++, "Reserve", "Dolffs"     , "prussian", "Division", 0),
  new CavalryUnit (unitCntr++, "Reserve", "Juergass"   , "prussian", "Division", 0),
  new CavalryUnit (unitCntr++, "Garde"  , "Alvensleben", "prussian", "Division", 0),

  new ArtilleryUnit (unitCntr++, "Reserve", "", "prussian", "Division", 0),                      

  // Russian
  new InfantryUnit (unitCntr++, "3rd"     , "Schowskoi" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "4th"     , "Puschnzk"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "5th"     , "Mesenzow"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "7th"     , "Talysin I" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "8th"     , "Urussow"   , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "9th"     , "Udom II"   , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "10th"    , "Leiwen"    , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "11th"    , "Gurgalow"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "12th"    , "Chowanski" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "13th"    , "Lidnfors"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "14th"    , "Helfreich" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "15th"    , "Kornilow"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "17th"    , "Pilar"     , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "18th"    , "Benardos"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "21st"    , "Laptew"    , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "22nd"    , "Schapski"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "24th"    , "Wuitsch"   , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "26th"    , "Paskiewitz", "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "27th"    , "Newjeroski", "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Av Gde"  , "Markow"    , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "1st Gren", "Zwilenief" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd Gren", "Sulima"    , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Mixed"   , "Kasakofski", "russian", "Division", 0),
  new InfantryUnit (unitCntr++, ""        , "Engelhart" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Glogau"  , "Kosen"     , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Militia" , "Muronzow"  , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Militia" , "Tirow"     , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "1st Gde" , "Rosen"     , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd Gde" , "Udom I"    , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, "Av Gde"  , "O' Rourke" , "russian", "Division", 0),
  new InfantryUnit (unitCntr++, ""        , "Harpe"     , "russian", "Division", 0),

  new CavalryUnit (unitCntr++, ""           , "Puschkin"  , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, ""           , "Denissiew" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Karpow"    , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, ""           , "Pahlen II" , "russian", "Brigade" , 0),
  new CavalryUnit (unitCntr++, "1st Cuir"   , "Deprerado" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Cuir"   , "Kretow"    , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "3rd Cuir"   , "Duka"      , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Ilowainski", "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Lt"         , "Tchalikow" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Hussars", "Lanskoi"   , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "3rd Dragons", "Pandshul"  , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Karpow II" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "1st Hussars", "Milesinow" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Ulan"       , "Lisanewit" , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, ""           , "Puschkin"  , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "4th Dragons", "Emanuel"   , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Av Gde"     , "Markow"    , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Chas"       , "Karpenko"  , "russian", "Brigade" , 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Mensdorf"  , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Platov"    , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, "Kossaks"    , "Thielman"  , "russian", "Brigade" , 0),
  new CavalryUnit (unitCntr++, "1st Dragon" , "Borosdin"  , "russian", "Division", 0),
  new CavalryUnit (unitCntr++, ""           , "Tschaplitz", "russian", "Brigade" , 0),
  new CavalryUnit (unitCntr++, ""           , "Krassofs"  , "russian", "Brigade" , 0),

  new ArtilleryUnit (unitCntr++, "Reserve", "", "russian", "Brigade", 0), 
  new ArtilleryUnit (unitCntr++, "Reserve", "", "russian", "Brigade", 0),

  // Swedish
  new InfantryUnit (unitCntr++, "1st"        , "Schutssnh", "russian", "Brigade", 0), 
  new InfantryUnit (unitCntr++, "2nd"        , "Reuterski", "russian", "Brigade", 0), 
  new InfantryUnit (unitCntr++, "3rd"        , "Braendstr", "russian", "Brigade", 0), 
  new InfantryUnit (unitCntr++, "4th"        , "Posse"    , "russian", "Brigade", 0), 
  new InfantryUnit (unitCntr++, "6th"        , "Boije"    , "russian", "Brigade", 0), 
  new CavalryUnit  (unitCntr++, "1st Reserve", ""         , "russian", "Brigade", 0), 
  new ArtilleryUnit (unitCntr++, "Reserve"   , ""         , "russian", "Brigade", 0), 

                   // Austrian
  new InfantryUnit (unitCntr++, "2nd"    , "Winpfen"  , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"    , "Greth"    , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd"    , "A Liechtn", "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"    , "Weissenw" , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd"    , "Murray"   , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"    , "Philipp"  , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd"    , "Hohenlohe", "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd Lt" , "Mezko"    , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd"    , "Mayer"    , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "1st Lt" , "M Liecthn", "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd Lt" , "Bubna"    , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "1st Res", "Chasteler", "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "2nd Res", "Bianchi"  , "austrian", "Division", 0),
  new InfantryUnit (unitCntr++, "3rd Res", "Civalart" , "austrian", "Division", 0),
                   
  new ArtilleryUnit (unitCntr++, "Res"   , "Reisner"  , "austrian", "Division", 0),
                   
  new CavalryUnit (unitCntr++, "1st"   , "Schneller", "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "1st"   , "Lederer"  , "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "1st"   , "Crennevil", "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "1st"   , "Ehrengde" , "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "1st Lt", "M Liechtn", "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "2nd Lt", "Bubna"    , "austrian", "Division", 0),
  new CavalryUnit (unitCntr++, "Cuir"  , "Nostitz"  , "austrian", "Division", 0),
];
                   

timeTrack = 
[
  {   
    day: "25-26 April",
    stacks: 
    [ {
        id: 1,
        x: 0,
        y: 62,
        sticky: false,
        formation: "column",
        facing: "E",
        units:
        [
          {
            commander: "Soult",
            unit: "Old Guard",
            nationality: "french",
            initiative: 4,
            bonus: "",
            commandCapacity: 6,
            subordinationValue: 3,
            commandingUnit: undefined
          },
          {
            commander: "Bessieres",
            unit: "Guard Cavalry",
            type: "cavalry",
            nationality: "french",
            initiative: 5,
            bonus: "",
            commandCapacity: 2,
            subordinationValue: 1,
            commandingUnit: undefined
          },
          {
            commander: "Napoleon",
            unit: "Armee du Nord",
            nationality: "french",
            initiative: 4,
            bonus: "*",
            commandCapacity: 10,
            subordinationValue: 4,
            commandingUnit: undefined
          },
          {
            commander: "Marmont",
            unit: "VI Corps",
            nationality: "french",
            initiative: 3,
            bonus: "",
            commandCapacity: 6,
            subordinationValue: 3,
            commandingUnit: undefined
          }
          // Russian Ic
          // Russian Ii
        ]
      }
    ]
  },
    
  {
    day: "27-28 April",
    stacks: 
    [
      {
        id: 2,
        x: 1,
        y: 78,
        sticky: false,
        formation: "column", 
        facing: "E",
        units:
        [
          {
            commander: "Bertrand",
            unit: "IV Corps",
            nationality: "french",
            initiative: 3,
            bonus: "*",
            commandCapacity: 6,
            subordinationValue: 2,
            commandingUnit: undefined
          }
        ]
      }
    ]
  }
]



      
      
