// SoN units and commanders

leaders = [
  new leader ("Nap", undefined, "Napoleon"       , "Emperor"        , "french", "infantry-leader", 4, true ,10, 6, "column", 0, 0, "NE"),
  new leader ("Dru", undefined, "Drouot"         , "Old Guard"      , "french", "infantry-leader", 4, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Sou", undefined, "Soult"          , "Old Guard"      , "french", "infantry-leader", 4, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Oud", undefined, "Oudinot"        , "I Young Guard"  , "french", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Mor", undefined, "Mortier"        , "II Young Guard" , "french", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader ("Van", undefined, "Vandamme"       , "I Corps"        , "french", "infantry-leader", 2, true , 4, 2, "column", 0, 0, "NE"),
  new leader ("Vic", undefined, "Victor"         , "II Corps"       , "french", "infantry-leader", 2, false, 6, 2, "column", 0, 0, "NE"),
  new leader ("Ney", undefined, "Ney"            , "III Corps"      , "french", "infantry-leader", 3, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Sou", undefined, "Souham"         , "III Corps"      , "french", "infantry-leader", 2, false, 6, 2, "column", 0, 0, "NE"),
  new leader ("Ber", undefined, "Betrand"        , "IV Corps"       , "french", "infantry-leader", 3, true,  6, 2, "column", 0, 0, "NE"),
  new leader ("Lau", undefined, "Lauriston"      , "V Corps"        , "french", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader ("Marm", undefined, "Marmont"        , "VI Corps"       , "french", "infantry-leader", 3, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Rey", undefined, "Reynier"        , "VII Corps"      , "french", "infantry-leader", 4, true , 6, 2, "column", 0, 0, "NE"),
  new leader ("Pon", undefined, "Poniatowski"    , "VIII Corps"     , "french", "infantry-leader", 4, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Aug", undefined, "Augereau"       , "IX Corps"       , "french", "infantry-leader", 2, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Mac", undefined, "MacDonald"      , "XI Corps"       , "french", "infantry-leader", 4, true , 6, 3, "column", 0, 0, "NE"),
  new leader ("Ger", undefined, "Gerard"         , "XI Corps"       , "french", "infantry-leader", 3, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("Oud2", undefined, "Oudinot"        , "XII Corps"      , "french", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Cyr", undefined, "St. Cyr"        , "XIV Corps"      , "french", "infantry-leader", 5, false, 6, 2, "column", 0, 0, "NE"),
  new leader ("Gir", undefined, "Girard"         , "Ad Hoc"         , "french", "infantry-leader", 3, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Eug", undefined, "Eugene"         , "Armee de l'Elbe", "french", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),            
  new leader ("Bess", undefined, "Bessieres"      , "Guard Cavalry"  , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Nans", undefined, "Nansouty"       , "Guard Cavalry"  , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Lat", undefined, "Latour-Maubourg", "I Cavalry"      , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Seb", undefined, "Sebastiani"     , "II Cavalry"     , "french", "cavalry-leader",  5, false, 3, 1, "column", 0, 0, "NE"),
  new leader ("Arr", undefined, "Arrighi"        , "III Cavalry"    , "french", "cavalry-leader",  5, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Kell", undefined, "Kellerman"      , "IV Cavalry"     , "french", "cavalry-leader",  4, false, 1, 1, "column", 0, 0, "NE"),
  new leader ("Lheri", undefined, "L'Heritier"     , "V Cavalry"      , "french", "cavalry-leader",  4, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Mur", undefined, "Murat"          , "Cavalry Reserve", "french", "cavalry-leader",  4, false, 6, 3, "column", 0, 0, "NE"),

  new leader ("Bluch", undefined, "Bluecher"  , "I Corps"    , "prussian", "infantry-leader", 4, true , 8, 3, "column", 0, 0, "NE"),
  new leader ("Kle", undefined, "Kleist"    , "II Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader ("Bul", undefined, "Bulow"     , "III Corps"  , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader ("Yor", undefined, "Yorck"     , "II Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader ("Tau", undefined, "Tauenzien" , "IV Corps"   , "prussian", "infantry-leader", 2, false, 5, 2, "column", 0, 0, "NE"),
  new leader ("Treu", undefined, "Truebezkov", "III Cavalry", "prussian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),
  new leader ("Kor", undefined, "Korff"     , "I Cavalry"  , "prussian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),

  new leader ("Schwarz", undefined, "Schwarzenberg", "XXXX"     , "austrian", "infantry-leader", 2, true , 6, 4, "column", 0, 0, "NE"),
  new leader ("Collo"  , undefined, "Colloredo"    , "I Corps"  , "austrian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Gyu"    , undefined, "Gyulai"       , "III Corps", "austrian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Meerv"  , undefined, "Meerveldt"    , "II Corps" , "austrian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Klen"   , undefined, "Klenau"       , "IV Corps" , "austrian", "infantry-leader", 1, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("HHomb"  , undefined, "Hesse Homburg", "Reserve"  , "austrian", "infantry-leader", 2, false, 6, 3, "column", 0, 0, "NE"),

  new leader ("Tolly" , undefined, "Barclay de Tolly" , ""                  , "russian", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader ("Benn"  , undefined, "Bennigsen"        , "I Corps"           , "russian", "infantry-leader", 2, false, 4, 4, "column", 0, 0, "NE"),
  new leader ("Doc"   , undefined, "Doctorov"         , "I Corps"           , "russian", "infantry-leader", 1, false, 6, 3, "column", 0, 0, "NE"),
  new leader ("Tolst" , undefined, "Ostermann-Tolstoj", "Militia"           , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Lang"  , undefined, "Langeron"         , ""                  , "russian", "infantry-leader", 2, false, 5, 4, "column", 0, 0, "NE"),
  new leader ("Ols"   , undefined, "Olsufiew"         , "IX Corps"          , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Priest", undefined, "St Priest"        , "VII Corps"         , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("Scherb", undefined, "Scherbatow"       , "VI Corps"          , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),
  new leader ("Kapz"  , undefined, "Kapzewitsch"      , "X Corps"           , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Sacken", undefined, "Osten-Sacken"     , "XI Corps"          , "russian", "infantry-leader", 3, true , 6, 2, "column", 0, 0, "NE"),
  new leader ("Wittg" , undefined, "Wittgenstein"     , ""                  , "russian", "infantry-leader", 2, false, 5, 3, "column", 0, 0, "NE"),
  new leader ("Gortch", undefined, "Gortchakow"       , "I Infantry"        , "russian", "infantry-leader", 1, false, 3, 2, "column", 0, 0, "NE"),
  new leader ("Eugen" , undefined, "Eugen"            , "II Infantry"       , "russian", "infantry-leader", 2, false, 2, 1, "column", 0, 0, "NE"),   
  new leader ("Konst" , undefined, "Konstantin"       , "Guards and Reserve", "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),    
  new leader ("Milo"  , undefined, "Miloradowitch"    , "II Corps"          , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("Raj"   , undefined, "Rajewski"         , "III Grenadiers"    , "russian", "infantry-leader", 1, false, 2, 1, "column", 0, 0, "NE"),   
  new leader ("Yermo" , undefined, "Yermolow"         , "V Guards"          , "russian", "infantry-leader", 1, false, 3, 1, "column", 0, 0, "NE"), 
  new leader ("Winzi" , undefined, "Winzingerode"     , "II Corps"          , "russian", "infantry-leader", 2, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("Woro"  , undefined, "Woronzow"         , "XIV Corps"         , "russian", "infantry-leader", 1, false, 4, 2, "column", 0, 0, "NE"),
  new leader ("Markov", undefined, "Markow"           , "IV Infantry"       , "russian", "infantry-leader", 4, false, 2, 1, "column", 0, 0, "NE"),             
  new leader ("Gali"  , undefined, "Galitzin"         , "II Cuirassiers"    , "russian", "cavalry-leader" , 4, false, 4, 1, "column", 0, 0, "NE"),
  new leader ("Pahlen", undefined, "Pahlen"           , "IV Cavalry"        , "russian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),
  new leader ("Wasi"  , undefined, "Wasiltchikow"     , "IV Cavalry"        , "russian", "cavalry-leader" , 4, false, 3, 1, "column", 0, 0, "NE"),

  new leader ("Berna", undefined, "Bernadotte", "XXXX"   , "swedish", "infantry-leader", 1, false, 4, 4, "column", 0, 0, "NE"),
  new leader ("Stedi", undefined, "Stedingk"  , "I Corps", "swedish", "infantry-leader", 1, false, 5, 2, "column", 0, 0, "NE")
];


var units = [
  new InfantryUnit ("1OG"     , "1st OG"  , "Roguet"      , "french", "Division", 0),
  new InfantryUnit ("2OG"     , "2nd OG"  , "Curial"      , "french", "Division", 0),
  new InfantryUnit ("2YGde"   , "2nd YGde", "Barrois"     , "french", "Division", 0),
  new InfantryUnit ("3YGde"   , "3rd YGde", "Delaborde"   , "french", "Division", 0),
  new InfantryUnit ("4YGde"   , "4th YGde", "Roguet"      , "french", "Division", 0),
  new InfantryUnit ("1FrInf"     , "1st"     , "Philippon"   , "french", "Division", 0),
  new InfantryUnit ("2FrInf"     , "2nd"     , "Dumonceau"   , "french", "Division", 0),
  new InfantryUnit ("3FrInf"     , "3rd"     , "Teste"       , "french", "Division", 0),
  new InfantryUnit ("4FrInf"     , "4th"     , "Dubreton"    , "french", "Division", 0),
  new InfantryUnit ("5FrInf"     , "5th"     , "Dufour"      , "french", "Division", 0),
  new InfantryUnit ("6FrInf"     , "6th"     , "Vial"        , "french", "Division", 0),
  new InfantryUnit ("8FrInf"     , "8th"     , "Brayer"      , "french", "Division", 0),
  new InfantryUnit ("9FrInf"     , "9th"     , "Brenier"     , "french", "Division", 0),
  new InfantryUnit ("10FrInf"    , "10th"    , "Albert"      , "french", "Division", 0),
  new InfantryUnit ("11FrInf"    , "11th"    , "Richard"     , "french", "Division", 0),
  new InfantryUnit ("13FrInf"    , "13rd"    , "Patchod"     , "french", "Division", 0),
  new InfantryUnit ("14FrInf"    , "14th"    , "Lorencez"    , "french", "Division", 0),
  new InfantryUnit ("16FrInf"    , "16th"    , "Maison"      , "french", "Division", 0),
  new InfantryUnit ("17FrInf"    , "17th"    , "Puthod"      , "french", "Division", 0),
  new InfantryUnit ("18FrInf"    , "18th"    , "Lagrange"    , "french", "Division", 0),
  new InfantryUnit ("19FrInf"    , "19th"    , "Rochambeau"  , "french", "Division", 0),
  new InfantryUnit ("20FrInf"    , "20th"    , "Compans"     , "french", "Division", 0),
  new InfantryUnit ("21FrInf"    , "21st"    , "Bonet"       , "french", "Division", 0),
  new InfantryUnit ("22FrInf"    , "22nd"    , "FrInfiederich"  , "french", "Division", 0),
  new InfantryUnit ("23FrInf"    , "23rd"    , "Laboissiere" , "french", "Division", 0),
  new InfantryUnit ("31FrInf"    , "31st"    , "Ledru des"   , "french", "Division", 0),
  new InfantryUnit ("32FrInf"    , "32nd"    , "Durutte"     , "french", "Division", 0),
  new InfantryUnit ("35FrInf"    , "35th"    , "FrInfassinet"   , "french", "Division", 0),
  new InfantryUnit ("36FrInf"    , "36th"    , "Charpentier" , "french", "Division", 0),
  new InfantryUnit ("42FrInf"    , "42nd"    , "Creutzer"    , "french", "Division", 0),
  new InfantryUnit ("43FrInf"    , "43rd"    , "Claparede"   , "french", "Division", 0),
  new InfantryUnit ("44FrInf"    , "44th"    , "Berthezene"  , "french", "Division", 0),
  new InfantryUnit ("45FrInf"    , "45th"    , "Razout"      , "french", "Division", 0),
  new InfantryUnit ("51FrInf"    , "51st"    , "Turreau"     , "french", "Division", 0),
  new InfantryUnit ("5FrInf"     , "52nd"    , "Semelle"     , "french", "Division", 0),
  new InfantryUnit ("Lef"        , "Lefol"   , ""            , "french", "Division", 0),

  new InfantryUnit ("Lapl", "Glogau"    , "Laplane"   , "french", "Division", 0),
  new InfantryUnit ("Duro", "Dresden"   , "Durosnel"  , "french", "Division", 0),
  new InfantryUnit ("Marg", "Leipzig"   , "Margaron"  , "french", "Division", 0),
  new InfantryUnit ("Lanu", "Magdeburg" , "Lanusse"   , "french", "Division", 0),
  new InfantryUnit ("Lemo", "Magdeburg" , "Lemoine"   , "french", "Division", 0),
  new InfantryUnit ("Laue", "Torgau"    , "Lauer"     , "french", "Division", 0),
  new InfantryUnit ("Lapo", "Wittenberg", "Lapoype"   , "french", "Division", 0),

  new CavalryUnit ("1FrCav", "1st Ornano"       , "french", "Division", 0),
  new CavalryUnit ("2FrCav", "2nd Lefebvre"     , "french", "Division", 0),
  new CavalryUnit ("3FrCav", "3rd Walther"      , "french", "Division", 0),
  new CavalryUnit ("6FrCav" , "6th Bruno"        , "french", "Division", 0),
  new CavalryUnit ("10FrCav", "10th Jacquet"     , "french", "Division", 0),
  new CavalryUnit ("21FrCav", "21st Corbineau"   , "french", "Division", 0),
  new CavalryUnit ("1LtFr"  , "1st Light Bruyere", "french", "Division", 0),
  new CavalryUnit ("2LtFr"  , "2nd Lt d'Hurbal"  , "french", "Division", 0),
  new CavalryUnit ("3LtFr"  , "3rd Lt Chastel"   , "french", "Division", 0),
  new CavalryUnit ("4LtFr"  , "4th Lt Exelmans"  , "french", "Division", 0),
  new CavalryUnit ("5LtFr"  , "5th Lt Lorge"     , "french", "Division", 0),
  new CavalryUnit ("6LtFr"  , "6th Lt Fournier"  , "french", "Division", 0),
  new CavalryUnit ("9LtFr"  , "9th Lt Subervie"  , "french", "Division", 0),
  new CavalryUnit ("1HvFr"  , "1st Hvy Bordessol", "french", "Division", 0),
  new CavalryUnit ("2HvFr"  , "2nd Hvy Wattier"  , "french", "Division", 0),
  new CavalryUnit ("3HvFr"  , "3rd Hvy Doumerc"  , "french", "Division", 0),
  new CavalryUnit ("4HvFr"  , "4th Hvy Defrance" , "french", "Division", 0),
  new CavalryUnit ("5HvFr"  , "5th Hvy Collaert" , "french", "Division", 0),
  new CavalryUnit ("6HvFr"  , "6th Hvy Milhaud"  , "french", "Division", 0),
  new ArtilleryUnit ("GdArt", "Guard Artillery"  , "french", "Division", 0),
  new ArtilleryUnit ("ArtFr1", "Artillery Reserve", "french", "Division", 0),
  new ArtilleryUnit ("ArtFr2", "Artillery Reserve", "french", "Division", 0),
  new ArtilleryUnit ("ArtFr3", "Artillery Reserve", "french", "Division", 0),

  new InfantryUnit ("15De"    , "15th", "Peyri"      , "german", "Division", 0),
  new InfantryUnit ("Lecoq"   , "24th", "Lecoq"      , "german", "Division", 0),
  new InfantryUnit ("25De"    , "25th", "Sahr"       , "german", "Division", 0),
  new InfantryUnit ("38De"    , "38th", "Franquemont", "german", "Division", 0),
  new InfantryUnit ("39De"    , "39th", "Marchand"   , "german", "Division", 0),
  new InfantryUnit ("IVDe"    , "IV"  , ""           , "german", "Division", 0),

  new CavalryUnit ("CavDe"   , ""        , "Briche-J" , "german", "Brigade", 0),
  new CavalryUnit ("25CavDe" , "25th Cav", "Norman"   , "german", "Brigade", 0),
  new CavalryUnit ("26CavDe", "26th Cav", "Gablenz"  , "german", "Brigade", 0),
  new CavalryUnit ("28CavDe", "28th Cav", "Montbrun" , "german", "Brigade", 0),
  new CavalryUnit ("29CavDe", "29th Cav", "Raglowich", "german", "Brigade", 0),

  // Prussians
  new InfantryUnit ("1PrInf"  , "1st"   , "Losthin"    , "prussian", "Division", 0),
  new InfantryUnit ("2PrInf"  , "2nd"   , "Warburg"    , "prussian", "Division", 0),
  new InfantryUnit ("3PrInf"  , "3rd"   , "H Homburg"  , "prussian", "Division", 0),
  new InfantryUnit ("4PrInf"  , "4th"   , "Thuemen"    , "prussian", "Division", 0),
  new InfantryUnit ("5PrInf"  , "5th"   , "Borstell"   , "prussian", "Division", 0),
  new InfantryUnit ("6PrInf"  , "6th"   , "Krafft"     , "prussian", "Division", 0),
  new InfantryUnit ("7PrInf"  , "7th"   , "Weltzien"   , "prussian", "Division", 0),
  new InfantryUnit ("8PrInf"  , "8th"   , "Girsa"      , "prussian", "Division", 0),
  new InfantryUnit ("9PrInf"  , "9th"   , "Kluex"      , "prussian", "Division", 0),
  new InfantryUnit ("10PrInf" , "10th"  , "Roeder"     , "prussian", "Division", 0),
  new InfantryUnit ("11PrInf" , "11th"  , "Zieten"     , "prussian", "Division", 0),
  new InfantryUnit ("12PrInf" , "12th"  , "August"     , "prussian", "Division", 0),
  new InfantryUnit ("Dobsch"  , "Lander", "Dobschutz"  , "prussian", "Division", 0),
  new InfantryUnit ("Hirsch"  , "Lander", "Hirschfeld" , "prussian", "Division", 0),
  new InfantryUnit ("Putlitz" , "Lander", "Putlitz"    , "prussian", "Division", 0),
  new InfantryUnit ("Wobeser" , "Lander", "Wobeser"    , "prussian", "Division", 0),
  new InfantryUnit ("InfAlven", "Garde" , "Alvensleben", "prussian", "Division", 0),

  new CavalryUnit ("Oppen"   , "Reserve", "Oppenheimer", "prussian", "Division", 0),
  new CavalryUnit ("Dolffs"  , "Reserve", "Dolffs"     , "prussian", "Division", 0),
  new CavalryUnit ("Juerg"   , "Reserve", "Juergass"   , "prussian", "Division", 0),
  new CavalryUnit ("CavAlven", "Garde"  , "Alvensleben", "prussian", "Division", 0),

  new ArtilleryUnit ("ArtPr", "Reserve", "", "prussian", "Division", 0),                      

  // Russian
  new InfantryUnit ("3RuInf"  , "3rd"     , "Schowskoi" , "russian", "Division", 0),
  new InfantryUnit ("4RuInf"  , "4th"     , "Puschnzk"  , "russian", "Division", 0),
  new InfantryUnit ("5RuInf"  , "5th"     , "Mesenzow"  , "russian", "Division", 0),
  new InfantryUnit ("7RuInf"  , "7th"     , "Talysin I" , "russian", "Division", 0),
  new InfantryUnit ("8RuInf"  , "8th"     , "Urussow"   , "russian", "Division", 0),
  new InfantryUnit ("9RuInf"  , "9th"     , "Udom II"   , "russian", "Division", 0),
  new InfantryUnit ("10RuInf" , "10th"    , "Leiwen"    , "russian", "Division", 0),
  new InfantryUnit ("11RuInf" , "11th"    , "Gurgalow"  , "russian", "Division", 0),
  new InfantryUnit ("12RuInf" , "12th"    , "Chowanski" , "russian", "Division", 0),
  new InfantryUnit ("13RuInf" , "13th"    , "Lidnfors"  , "russian", "Division", 0),
  new InfantryUnit ("14RuInf" , "14th"    , "Helfreich" , "russian", "Division", 0),
  new InfantryUnit ("15RuInf" , "15th"    , "Kornilow"  , "russian", "Division", 0),
  new InfantryUnit ("17RuInf" , "17th"    , "Pilar"     , "russian", "Division", 0),
  new InfantryUnit ("18RuInf" , "18th"    , "Benardos"  , "russian", "Division", 0),
  new InfantryUnit ("21RuInf" , "21st"    , "Laptew"    , "russian", "Division", 0),
  new InfantryUnit ("22RuInf" , "22nd"    , "Schapski"  , "russian", "Division", 0),
  new InfantryUnit ("24RuInf" , "24th"    , "Wuitsch"   , "russian", "Division", 0),
  new InfantryUnit ("26RuInf" , "26th"    , "Paskiewitz", "russian", "Division", 0),
  new InfantryUnit ("27RuInf" , "27th"    , "Newjeroski", "russian", "Division", 0),
  new InfantryUnit ("MarkowInf", "Av Gde"  , "Markow"    , "russian", "Division", 0),
  new InfantryUnit ("1RuGren" , "1st Gren", "Zwilenief" , "russian", "Division", 0),
  new InfantryUnit ("2RuGren" , "2nd Gren", "Sulima"    , "russian", "Division", 0),
  new InfantryUnit ("MixInf"  , "Mixed"   , "Kasakofski", "russian", "Division", 0),
  new InfantryUnit ("Engel"   , ""        , "Engelhart" , "russian", "Division", 0),
  new InfantryUnit ("Gloga"   , "Glogau"  , "Kosen"     , "russian", "Division", 0),
  new InfantryUnit ("Muronz"  , "Militia" , "Muronzow"  , "russian", "Division", 0),
  new InfantryUnit ("Tirow"   , "Militia" , "Tirow"     , "russian", "Division", 0),
  new InfantryUnit ("1RuGde"  , "1st Gde" , "Rosen"     , "russian", "Division", 0),
  new InfantryUnit ("2RuGde"  , "2nd Gde" , "Udom I"    , "russian", "Division", 0),
  new InfantryUnit ("Rourke"  , "Av Gde"  , "O' Rourke" , "russian", "Division", 0),
  new InfantryUnit ("Harpe"   , ""        , "Harpe"     , "russian", "Division", 0),

  new CavalryUnit ("Puschkin", ""           , "Puschkin"  , "russian", "Division", 0),
  new CavalryUnit ("Deniss"  , ""           , "Denissiew" , "russian", "Division", 0),
  new CavalryUnit ("Karpow"  , "Kossaks"    , "Karpow"    , "russian", "Division", 0),
  new CavalryUnit ("PahlenII", ""           , "Pahlen II" , "russian", "Brigade" , 0),
  new CavalryUnit ("1RuCuir" , "1st Cuir"   , "Deprerado" , "russian", "Division", 0),
  new CavalryUnit ("2RuCuir" , "2nd Cuir"   , "Kretow"    , "russian", "Division", 0),
  new CavalryUnit ("3RuCuir" , "3rd Cuir"   , "Duka"      , "russian", "Division", 0),
  new CavalryUnit ("Ilow"    , "Kossaks"    , "Ilowainski", "russian", "Division", 0),
  new CavalryUnit ("Tchali"  , "Lt"         , "Tchalikow" , "russian", "Division", 0),
  new CavalryUnit ("Lansk"   , "2nd Hussars", "Lanskoi"   , "russian", "Division", 0),
  new CavalryUnit ("Pandsh"  , "3rd Dragons", "Pandshul"  , "russian", "Division", 0),
  new CavalryUnit ("KarpowII", "Kossaks"    , "Karpow II" , "russian", "Division", 0),
  new CavalryUnit ("Mile"    , "1st Hussars", "Milesinow" , "russian", "Division", 0),
  new CavalryUnit ("Lisan"   , "Ulan"       , "Lisanewit" , "russian", "Division", 0),
  new CavalryUnit ("Pushck"  , ""           , "Puschkin"  , "russian", "Division", 0),
  new CavalryUnit ("Emanuel" , "4th Dragons", "Emanuel"   , "russian", "Division", 0),
  new CavalryUnit ("MarkowCav", "Av Gde"     , "Markow"    , "russian", "Division", 0),
  new CavalryUnit ("Karpen"  , "Chas"       , "Karpenko"  , "russian", "Brigade" , 0),
  new CavalryUnit ("Mensd"   , "Kossaks"    , "Mensdorf"  , "russian", "Division", 0),
  new CavalryUnit ("Platov"  , "Kossaks"    , "Platov"    , "russian", "Division", 0),
  new CavalryUnit ("Thielm"  , "Kossaks"    , "Thielman"  , "russian", "Brigade" , 0),
  new CavalryUnit ("Boros"   , "1st Dragon" , "Borosdin"  , "russian", "Division", 0),
  new CavalryUnit ("Tschapl" , ""           , "Tschaplitz", "russian", "Brigade" , 0),
  new CavalryUnit ("Krass"   , ""           , "Krassofs"  , "russian", "Brigade" , 0),

  new ArtilleryUnit ("RuArt1", "Reserve", "", "russian", "Brigade", 0), 
  new ArtilleryUnit ("RuArt2", "Reserve", "", "russian", "Brigade", 0),

  // Swedish
  new InfantryUnit ("1SwInf", "1st"        , "Schutssnh", "swedish", "Brigade", 0), 
  new InfantryUnit ("2SwInf", "2nd"        , "Reuterski", "swedish", "Brigade", 0), 
  new InfantryUnit ("3SwInf", "3rd"        , "Braendstr", "swedish", "Brigade", 0), 
  new InfantryUnit ("4SwInf", "4th"        , "Posse"    , "swedish", "Brigade", 0), 
  new InfantryUnit ("6SwInf", "6th"        , "Boije"    , "swedish", "Brigade", 0), 
  new CavalryUnit  ("1SwCav", "1st Reserve", ""         , "swedish", "Brigade", 0), 
  new ArtilleryUnit ("SwArt", "Reserve"   , ""         , "swedish", "Brigade", 0), 

                   // Austrian
  new InfantryUnit ("Wimpf"    , "2nd"    , "Winpfen"  , "austrian", "Division", 0),
  new InfantryUnit ("Greth"    , "3rd"    , "Greth"    , "austrian", "Division", 0),
  new InfantryUnit ("ALiech"   , "2nd"    , "A Liechtn", "austrian", "Division", 0),
  new InfantryUnit ("Weiss"    , "3rd"    , "Weissenw" , "austrian", "Division", 0),
  new InfantryUnit ("Murray"   , "2nd"    , "Murray"   , "austrian", "Division", 0),
  new InfantryUnit ("Philipp"  , "3rd"    , "Philipp"  , "austrian", "Division", 0),
  new InfantryUnit ("Hohe"     , "2nd"    , "Hohenlohe", "austrian", "Division", 0),
  new InfantryUnit ("Mezko"    , "3rd Lt" , "Mezko"    , "austrian", "Division", 0),
  new InfantryUnit ("Mayer"    , "3rd"    , "Mayer"    , "austrian", "Division", 0),
  new InfantryUnit ("MliechInf", "1st Lt" , "M Liecthn", "austrian", "Division", 0),
  new InfantryUnit ("BubnaInf" , "2nd Lt" , "Bubna"    , "austrian", "Division", 0),
  new InfantryUnit ("Chastel"  , "1st Res", "Chasteler", "austrian", "Division", 0),
  new InfantryUnit ("Bianchi"  , "2nd Res", "Bianchi"  , "austrian", "Division", 0),
  new InfantryUnit ("Cival"    , "3rd Res", "Civalart" , "austrian", "Division", 0),
                   
  new ArtilleryUnit ("AuArt", "Res"   , "Reisner"  , "austrian", "Division", 0),
                   
  new CavalryUnit ("Schnell"  , "1st"   , "Schneller", "austrian", "Division", 0),
  new CavalryUnit ("Lederer"  , "1st"   , "Lederer"  , "austrian", "Division", 0),
  new CavalryUnit ("Crennev"  , "1st"   , "Crennevil", "austrian", "Division", 0),
  new CavalryUnit ("Ehrengde" , "1st"   , "Ehrengde" , "austrian", "Division", 0),
  new CavalryUnit ("MLiechCav", "1st Lt", "M Liechtn", "austrian", "Division", 0),
  new CavalryUnit ("BubnaCav" , "2nd Lt", "Bubna"    , "austrian", "Division", 0),
  new CavalryUnit ("Nostitz"  , "Cuir"  , "Nostitz"  , "austrian", "Division", 0),
];
                   
